# Generated by Django 6.0 on 2026-01-02 18:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionClientes', '0002_usuarioempresa'),
        ('gestionIdentificacion', '0008_t_beneficiario'),
        ('parametros', '0007_alter_t_banco_codigo_br_alter_t_banco_codigo_fintech'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_contrato', models.BigIntegerField(verbose_name='Codigo contrato')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha ingreso')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('periodo_vac', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Periodo de vacaciones')),
                ('codigo_interno', models.CharField(blank=True, max_length=16, null=True)),
                ('procedimiento', models.CharField(choices=[('1', 'Procentimiento 1'), ('2', 'Procedimiento 2')], max_length=1)),
                ('porcentaje_retencion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido'), ('T', 'Terminado')], default='A', max_length=1)),
                ('cesantias', models.CharField(choices=[('L50', 'Ley 50'), ('RT', 'Regimen Tradicional'), ('I', 'Integral'), ('A', 'Aprendices')], max_length=3)),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_banco', verbose_name='Banco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionClientes.t_empresa', verbose_name='Empresa')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionIdentificacion.t_identificacion', verbose_name='Identificacion')),
                ('subtipo_cotizante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_subtipo_cotizante', verbose_name='Subtipo cotizante')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_contrato', verbose_name='Tipo de contrato')),
                ('tipo_cotizante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_cotizante', verbose_name='Tipo cotizante')),
                ('tipo_salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_salario', verbose_name='Tipo de salario')),
            ],
            options={
                'unique_together': {('empresa', 'cod_contrato')},
            },
        ),
    ]
