# Generated by Django 6.0 on 2026-01-02 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_contrato',
            name='porcentaje_retencion',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje retencion'),
        ),
    ]
