# Generated by Django 6.0 on 2026-01-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0003_t_contrato_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_contrato_banco',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de cuenta'),
        ),
    ]
