# Generated by Django 6.0 on 2026-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0004_t_contrato_banco_numero_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_contrato_banco',
            name='retroactivo',
        ),
        migrations.AlterField(
            model_name='t_contrato_banco',
            name='cuenta',
            field=models.CharField(choices=[('A', 'Ahorro'), ('C', 'Corriente')], max_length=20, verbose_name='Tipo Cuenta'),
        ),
    ]
