# Generated by Django 6.0 on 2026-01-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0005_remove_t_contrato_banco_retroactivo_and_more'),
        ('parametros', '0009_alter_t_entidadesss_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_contrato_entidadesss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidad', models.CharField(choices=[('AFP', 'AFP'), ('EPS', 'EPS'), ('CCF', 'Caja de compensacion'), ('ARL', 'ARL')], max_length=10, verbose_name='Tipo entidad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionContratos.t_contrato', verbose_name='Contrato')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_entidadesss', verbose_name='Entidad')),
            ],
        ),
    ]
