# Generated by Django 6.0 on 2026-01-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0006_t_contrato_entidadesss'),
        ('parametros', '0009_alter_t_entidadesss_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_contrato_salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salario')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('retroactivo', models.BooleanField(default=True, verbose_name='Retroactivo')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionContratos.t_contrato', verbose_name='Contrato')),
                ('tipo_salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_salario', verbose_name='Tipo de salario')),
            ],
        ),
    ]
