# Generated by Django 6.0 on 2026-01-04 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0007_t_contrato_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_contrato_deducibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_deducible', models.CharField(choices=[('DED', 'Dependiente'), ('MED', 'Medicina prepagada'), ('VIV', 'Vivienda')], verbose_name='Tipo deducible')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionContratos.t_contrato', verbose_name='Contrato')),
            ],
        ),
    ]
