# Generated by Django 6.0 on 2026-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0008_t_contrato_deducibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_contrato_deducibles',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
