# Generated by Django 6.0 on 2026-01-07 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0009_t_contrato_deducibles_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_contrato',
            name='porcentaje_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje retencion'),
        ),
    ]
