# Generated by Django 6.0 on 2026-01-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0010_alter_t_contrato_porcentaje_retencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_contrato_deducibles',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='t_contrato_salario',
            name='salario',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Salario'),
        ),
    ]
