# Generated by Django 6.0 on 2026-01-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0011_alter_t_contrato_deducibles_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_contrato',
            name='banco',
        ),
    ]
