# Generated by Django 6.0 on 2026-01-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0012_remove_t_contrato_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_contrato_entidadesss',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='t_contrato_entidadesss',
            name='tipo_entidad',
            field=models.CharField(choices=[('AFP', 'AFP'), ('EPS', 'EPS'), ('CCF', 'CCF'), ('ARL', 'ARL')], max_length=10, verbose_name='Tipo entidad'),
        ),
    ]
