# Generated by Django 6.0 on 2026-01-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0013_alter_t_contrato_entidadesss_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_contrato_deducibles',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='t_contrato_entidadesss',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
    ]
