# Generated by Django 6.0 on 2026-01-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0014_alter_t_contrato_deducibles_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_contrato',
            name='tipo_salario',
        ),
    ]
