# Generated by Django 6.0 on 2026-01-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0015_remove_t_contrato_tipo_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_contrato',
            name='cesantias',
            field=models.CharField(choices=[('L50', 'LEY 50'), ('RT', 'REGIMEN TRADICIONAL'), ('I', 'INTEGRAL'), ('A', 'APRENDICES')], max_length=3),
        ),
        migrations.AlterField(
            model_name='t_contrato',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('S', 'SUSPENDIDO'), ('T', 'TERMINADO')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='t_contrato',
            name='procedimiento',
            field=models.CharField(choices=[('1', 'PROCEDIMIENTO 1'), ('2', 'PROCEDIMIENTO 2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='t_contrato_banco',
            name='cuenta',
            field=models.CharField(choices=[('A', 'AHORRO'), ('C', 'CORRIENTE')], max_length=20, verbose_name='Tipo Cuenta'),
        ),
        migrations.AlterField(
            model_name='t_contrato_deducibles',
            name='tipo_deducible',
            field=models.CharField(choices=[('DED', 'DEPENDIENTE'), ('MED', 'MEDICINA PREPAGADA'), ('VIV', 'VIVIENDA')], verbose_name='Tipo deducible'),
        ),
    ]
