# Generated by Django 6.0 on 2026-01-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0016_alter_t_contrato_cesantias_alter_t_contrato_estado_and_more'),
        ('parametros', '0014_remove_t_tipo_nomina_asigna_contrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_contrato',
            name='tipo_nomina',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_nomina', verbose_name='Tipo de nomina'),
            preserve_default=False,
        ),
    ]
