# Generated by Django 6.0 on 2026-01-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0017_t_contrato_tipo_nomina'),
        ('parametros', '0014_remove_t_tipo_nomina_asigna_contrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_contrato',
            name='tipo_nomina',
            field=models.ForeignKey(limit_choices_to={'asigna_contrato': True}, on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_nomina', verbose_name='Tipo de nomina'),
        ),
    ]
