# Generated by Django 6.0 on 2026-01-12 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0018_alter_t_contrato_tipo_nomina'),
        ('parametros', '0016_parametrodetalle_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_contrato',
            name='motivo_retiro',
            field=models.ForeignKey(blank=True, limit_choices_to={'parametro.codigo': 'RET'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.parametrodetalle', verbose_name='Motivo de retito'),
        ),
    ]
