# Generated by Django 6.0 on 2026-01-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0020_t_contrato_fecha_ret_alter_t_contrato_motivo_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_contrato',
            name='sabado_habil',
            field=models.BooleanField(default=False, verbose_name='Sábado hábil'),
        ),
    ]
