# Generated by Django 6.0 on 2025-12-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_tipo_contrato',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
