# Generated by Django 6.0 on 2025-12-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_alter_t_tipo_contrato_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_tipo_salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.CharField(max_length=50, verbose_name='Tipo de salario')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
