# Generated by Django 6.0 on 2025-12-30 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_t_tipo_cotizante'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_subtipo_cotizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('codigo_cotizante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtipos', to='parametros.t_tipo_cotizante', verbose_name='Codigo Cotizante')),
            ],
        ),
    ]
