# Generated by Django 6.0 on 2025-12-30 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_t_subtipo_cotizante'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=200, verbose_name='Banco')),
                ('codigo_ach', models.CharField(blank=True, max_length=3, null=True, verbose_name='Codigo ACH')),
                ('codigo_pse', models.CharField(blank=True, max_length=4, null=True, verbose_name='Codigo PSE')),
                ('codigo_br', models.CharField(blank=True, max_length=2, null=True, verbose_name='Codigo PSE')),
                ('codigo_fintech', models.CharField(blank=True, max_length=4, null=True, verbose_name='Codigo PSE')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='t_subtipo_cotizante',
            name='codigo_cotizante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtipos', to='parametros.t_tipo_cotizante', verbose_name='Cotizante'),
        ),
    ]
