# Generated by Django 6.0 on 2025-12-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_t_banco_alter_t_subtipo_cotizante_codigo_cotizante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_banco',
            name='codigo_br',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Codigo BR'),
        ),
        migrations.AlterField(
            model_name='t_banco',
            name='codigo_fintech',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Codigo FINTECH'),
        ),
    ]
