# Generated by Django 6.0 on 2026-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_alter_t_banco_codigo_br_alter_t_banco_codigo_fintech'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_entidadesss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EPS', 'EPS'), ('AFP', 'AFP'), ('CCF', 'Caja compensacion'), ('ARL', 'ARL')], max_length=3)),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo')),
                ('nit', models.CharField(max_length=16, verbose_name='Nit')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
