# Generated by Django 6.0 on 2026-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_t_entidadesss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_entidadesss',
            name='nit',
            field=models.CharField(max_length=16, verbose_name='Nit Entidad'),
        ),
    ]
