# Generated by Django 6.0 on 2026-01-04 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConceptos', '0001_initial'),
        ('parametros', '0009_alter_t_entidadesss_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_conceptos_salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConceptos.t_conceptos', verbose_name='Concepto')),
                ('tipo_salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_salario', verbose_name='Tipo salario')),
            ],
        ),
    ]
