# Generated by Django 6.0 on 2026-01-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0010_t_conceptos_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_conceptos_salario',
            name='tipo_salario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_salario', unique=True, verbose_name='Tipo salario'),
        ),
    ]
