# Generated by Django 6.0 on 2026-01-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0012_t_tipo_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_tipo_nomina',
            name='asigna_contrao',
            field=models.BooleanField(default=True, verbose_name='Se asigna a contrato?'),
        ),
    ]
