# Generated by Django 6.0 on 2026-01-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0013_t_tipo_nomina_asigna_contrao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_tipo_nomina',
            name='asigna_contrao',
        ),
        migrations.AddField(
            model_name='t_tipo_nomina',
            name='asigna_contrato',
            field=models.BooleanField(default=True, verbose_name='Se asigna a contrato'),
        ),
    ]
