# Generated by Django 6.0 on 2026-01-11 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0014_remove_t_tipo_nomina_asigna_contrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('valor_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='parametros.parametrogeneral')),
            ],
            options={
                'unique_together': {('parametro', 'codigo')},
            },
        ),
    ]
