# Generated by Django 6.0 on 2026-01-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0015_parametrogeneral_parametrodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrodetalle',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrodetalle',
            name='user_creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parametrogeneral',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrogeneral',
            name='user_creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
