# Generated by Django 6.0 on 2026-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0016_parametrodetalle_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrodetalle',
            name='valor_numerico',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
