# Generated by Django 6.0 on 2026-01-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0017_alter_parametrodetalle_valor_numerico'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_calendario_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabado_habil', models.BooleanField(verbose_name='Sábado hábil')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('habil', models.BooleanField(default=False, verbose_name='Habil')),
            ],
            options={
                'unique_together': {('sabado_habil', 'anio', 'mes', 'fecha', 'habil')},
            },
        ),
    ]
