# Generated by Django 6.0 on 2026-01-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0018_t_calendario_laboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrodetalle',
            name='valor_numerico2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='parametrodetalle',
            name='valor_numerico3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='parametrodetalle',
            name='valor_texto2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parametrodetalle',
            name='valor_texto3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
