# Generated by Django 6.0 on 2026-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNovedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_novedad_temporal',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Base'),
        ),
        migrations.AlterField(
            model_name='t_novedad_temporal',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Valor'),
        ),
    ]
