# Generated by Django 6.0 on 2026-01-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConceptos', '0009_alter_t_concepto_empresa_sin_valor'),
        ('gestionContratos', '0020_t_contrato_fecha_ret_alter_t_contrato_motivo_retiro'),
        ('gestionNovedades', '0002_alter_t_novedad_temporal_base_and_more'),
        ('parametros', '0017_alter_parametrodetalle_valor_numerico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_novedad_temporal',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='t_novedad_temporal',
            name='fecha_inicio',
        ),
        migrations.CreateModel(
            name='t_novedad_fija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Unidad')),
                ('base', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Base')),
                ('valor', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Valor')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConceptos.t_concepto_empresa', verbose_name='Concepto')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionContratos.t_contrato', verbose_name='Contrato')),
                ('tipo_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_nomina', verbose_name='Tipo de nómina')),
            ],
        ),
    ]
