# Generated by Django 6.0 on 2026-01-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConceptos', '0009_alter_t_concepto_empresa_sin_valor'),
        ('gestionContratos', '0020_t_contrato_fecha_ret_alter_t_contrato_motivo_retiro'),
        ('gestionNomina', '0015_alter_t_proceso_nomina_estado'),
        ('gestionNovedades', '0003_remove_t_novedad_temporal_fecha_fin_and_more'),
        ('parametros', '0017_alter_parametrodetalle_valor_numerico'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_novedad_fija_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('periodo', models.IntegerField(verbose_name='Periodo')),
                ('unidad', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Unidad')),
                ('base', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Base')),
                ('valor', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Valor')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('acumulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionNomina.t_acumulado_empleado_def', verbose_name='Acumulado')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConceptos.t_concepto_empresa', verbose_name='Concepto')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionContratos.t_contrato', verbose_name='Contrato')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionNovedades.t_novedad_fija', verbose_name='Novedad')),
                ('periodo_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionNomina.t_periodo_nomina', verbose_name='Periodo Nomina')),
                ('tipo_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_nomina', verbose_name='Tipo de nómina')),
            ],
        ),
    ]
