# Generated by Django 6.0 on 2025-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_tipo_ide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ide', models.IntegerField()),
                ('desc_ide', models.CharField(max_length=32)),
                ('estado_ide', models.BooleanField()),
                ('user_creator', models.CharField(max_length=50)),
                ('date_created', models.DateField()),
            ],
        ),
    ]
