# Generated by Django 6.0 on 2025-12-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionIdentificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_tipo_ide',
            name='cod_ide',
            field=models.CharField(max_length=8),
        ),
    ]
