# Generated by Django 6.0 on 2025-12-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionIdentificacion', '0002_alter_t_tipo_ide_cod_ide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_tipo_ide',
            name='user_creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
