# Generated by Django 6.0 on 2025-12-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionIdentificacion', '0003_alter_t_tipo_ide_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_tipo_ide',
            name='cod_ide',
            field=models.CharField(max_length=8, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='t_tipo_ide',
            name='desc_ide',
            field=models.CharField(max_length=32, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='t_tipo_ide',
            name='estado_ide',
            field=models.BooleanField(verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='t_identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=24, verbose_name='Numero documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha nacimiento')),
                ('fecha_exp_doc', models.DateField(verbose_name='Fecha expedicion documento')),
                ('telefono', models.IntegerField(max_length=20, verbose_name='Telefono')),
                ('celular', models.IntegerField(max_length=20, verbose_name='Celular')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('estado_civil', models.IntegerField(choices=[(1, 'SOLTER@'), (2, 'CASAD@'), (3, 'DIVORCIAD@'), (4, 'UNION LIBRE'), (5, 'VIUD@')], max_length=3, verbose_name='Estado civil')),
                ('genero', models.IntegerField(choices=[(1, 'FEMENINO'), (2, 'MASCULINO'), (3, 'NO DEFINIDO')], max_length=3, verbose_name='Genero')),
                ('correo_personal', models.EmailField(max_length=254, verbose_name='Correo personal')),
                ('correo_coorporativo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo coorporativo')),
                ('tipo_ide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='gestionIdentificacion.t_tipo_ide', verbose_name='Tipo identificación')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo_ide', 'identificacion'), name='unique_tipo_numero')],
            },
        ),
    ]
