# Generated by Django 6.0 on 2025-12-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionIdentificacion', '0004_alter_t_tipo_ide_cod_ide_alter_t_tipo_ide_desc_ide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_identificacion',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'FEMENINO'), (2, 'MASCULINO'), (3, 'NO DEFINIDO')], verbose_name='Genero'),
        ),
    ]
