# Generated by Django 6.0 on 2025-12-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionIdentificacion', '0005_alter_t_identificacion_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_identificacion',
            name='celular',
            field=models.IntegerField(verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='t_identificacion',
            name='estado_civil',
            field=models.IntegerField(blank=True, choices=[(1, 'SOLTER@'), (2, 'CASAD@'), (3, 'DIVORCIAD@'), (4, 'UNION LIBRE'), (5, 'VIUD@')], null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='t_identificacion',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'FEMENINO'), (2, 'MASCULINO'), (3, 'NO DEFINIDO')], null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='t_identificacion',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
