# Generated by Django 6.0 on 2025-12-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionIdentificacion', '0007_alter_t_identificacion_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden_beneficiario', models.CharField(max_length=24, verbose_name='Identificacion beneficiario')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha nacimiento')),
                ('parentesco', models.IntegerField(blank=True, choices=[('', 'Seleccione una opcion '), (1, 'MADRE'), (2, 'PADRE'), (3, 'HIJO'), (4, 'CONYUGUE')], null=True, verbose_name='Parentesco')),
                ('exogena', models.BooleanField(default=True, verbose_name='Exogena')),
                ('iden_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='gestionIdentificacion.t_identificacion', verbose_name='Identificacion titular')),
                ('tipo_ide_ben', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIdentificacion.t_tipo_ide', verbose_name='Tipo identificación')),
            ],
        ),
    ]
