# Generated by Django 6.0 on 2026-01-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionIdentificacion', '0008_t_beneficiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_identificacion',
            name='estado_civil',
            field=models.IntegerField(blank=True, choices=[('', 'Seleccion una opcion '), (1, 'SOLTERO(A)'), (2, 'CASADO(A)'), (3, 'DIVORCIADO(A)'), (4, 'UNION LIBRE'), (5, 'VIUDO(A)')], null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='t_identificacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono'),
        ),
    ]
