# Generated by Django 6.0 on 2026-01-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionClientes', '0005_t_empresa_digito_verificacion_and_more'),
        ('parametros', '0014_remove_t_tipo_nomina_asigna_contrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_periodo_nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código período')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('periodo', models.IntegerField(verbose_name='Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionClientes.t_empresa', verbose_name='Empresa')),
                ('tipo_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_nomina', verbose_name='Tipo de nómina')),
            ],
            options={
                'ordering': ['anio', 'mes', 'periodo'],
                'unique_together': {('empresa', 'tipo_nomina', 'anio', 'mes', 'periodo')},
            },
        ),
    ]
