# Generated by Django 6.0 on 2026-01-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_periodo_nomina',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código período'),
        ),
    ]
