# Generated by Django 6.0 on 2026-01-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0005_t_empresa_digito_verificacion_and_more'),
        ('gestionConceptos', '0006_alter_t_conceptos_tipo_concepto'),
        ('gestionNomina', '0002_alter_t_periodo_nomina_codigo'),
        ('parametros', '0016_parametrodetalle_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_periodo_nomina',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_periodo_nomina',
            name='user_creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='t_logica_calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(verbose_name='Periodo')),
                ('logica', models.CharField(blank=True, max_length=200, null=True)),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConceptos.t_concepto_empresa', verbose_name='Concepto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionClientes.t_empresa', verbose_name='Empresa')),
                ('modulo', models.ForeignKey(blank=True, limit_choices_to={'parametro__codigo': 'MOD'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.parametrodetalle', verbose_name='Motivo de retito')),
                ('tipo_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.t_tipo_nomina', verbose_name='Tipo de Nomina')),
            ],
            options={
                'verbose_name': 'Lógica de cálculo',
                'verbose_name_plural': 'Lógicas de cálculo',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo_nomina', 'periodo', 'concepto'), name='uq_logica_empresa_nomina_periodo_concepto')],
            },
        ),
    ]
