# Generated by Django 6.0 on 2026-01-13 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0003_t_periodo_nomina_date_created_and_more'),
        ('parametros', '0016_parametrodetalle_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_logica_calculo',
            name='orden',
            field=models.IntegerField(default=1, verbose_name='Orden'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_logica_calculo',
            name='modulo',
            field=models.ForeignKey(blank=True, limit_choices_to={'parametro__codigo': 'MOD'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.parametrodetalle', verbose_name='Modulo'),
        ),
    ]
