# Generated by Django 6.0 on 2026-01-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0005_t_acumulado_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_periodo_nomina',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
