# Generated by Django 6.0 on 2026-01-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0006_t_periodo_nomina_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_proceso_nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'PROCESANDO'), ('F', 'FINALIZADO'), ('X', 'ERROR')], default='P', max_length=1, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionNomina.t_periodo_nomina', verbose_name='Periodo nómina')),
            ],
        ),
    ]
