# Generated by Django 6.0 on 2026-01-16 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0007_t_proceso_nomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_logica_calculo_filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50, verbose_name='Campo a evaluar')),
                ('operador', models.CharField(max_length=20, verbose_name='Operador')),
                ('valor', models.CharField(max_length=200, verbose_name='Valor')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('logica_calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros', to='gestionNomina.t_logica_calculo', verbose_name='Lógica de cálculo')),
            ],
        ),
    ]
