# Generated by Django 6.0 on 2026-01-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0008_t_logica_calculo_filtro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_logica_calculo_filtro',
            name='operador',
            field=models.CharField(choices=[('IN', 'En lista'), ('NOT_IN', 'No en lista')], max_length=20, verbose_name='Operador'),
        ),
    ]
