# Generated by Django 6.0 on 2026-01-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0009_alter_t_logica_calculo_filtro_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_logica_calculo_filtro',
            name='valor',
            field=models.IntegerField(verbose_name='Valor'),
        ),
    ]
