# Generated by Django 6.0 on 2026-01-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0010_alter_t_logica_calculo_filtro_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_acumulado_empleado',
            name='periodo_nomina',
            field=models.ForeignKey(default=125, on_delete=django.db.models.deletion.CASCADE, to='gestionNomina.t_periodo_nomina', verbose_name='Periodo Nomina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_logica_calculo_filtro',
            name='operador',
            field=models.CharField(choices=[('IN', 'EN LISTA'), ('NOT_IN', 'NO EN LA LISTA')], max_length=20, verbose_name='Operador'),
        ),
    ]
