# Generated by Django 6.0 on 2026-01-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0011_t_acumulado_empleado_periodo_nomina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_proceso_nomina',
            name='progreso',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Progreso (%)'),
        ),
    ]
