# Generated by Django 6.0 on 2026-01-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0013_alter_t_proceso_nomina_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_acumulado_empleado',
            name='novedad_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='t_acumulado_empleado_def',
            name='novedad_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
