# Generated by Django 6.0 on 2026-01-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0014_t_acumulado_empleado_novedad_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_proceso_nomina',
            name='estado',
            field=models.CharField(choices=[('P', 'PROCESANDO'), ('F', 'FINALIZADO'), ('X', 'ERROR'), ('C', 'CERRADO'), ('R', 'REVERSADO')], default='P', max_length=1, verbose_name='Estado'),
        ),
    ]
