# Generated by Django 6.0 on 2026-01-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionNomina', '0015_alter_t_proceso_nomina_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_logica_calculo_filtro',
            name='logica_calculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filtros', to='gestionNomina.t_logica_calculo', verbose_name='Lógica de cálculo'),
        ),
        migrations.CreateModel(
            name='t_logica_calculo_parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.CharField(choices=[('A', '11 MESES CERRADOS + 1 ABIERTO'), ('B', '12 MESES CERRADOS'), ('C', '12 MESES CERRADOS + 1 ABIERTO')], max_length=2, verbose_name='Promedio variable')),
                ('vac_mes_sig', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='Paga vacaciones mes siguente')),
                ('paga_31', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='Paga 31')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('logica_calculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='gestionNomina.t_logica_calculo', verbose_name='Lógica de cálculo')),
            ],
        ),
    ]
