# Generated by Django 6.0 on 2026-01-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionContratos', '0021_t_contrato_sabado_habil'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_ciclos_vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio del ciclo')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin del ciclo')),
                ('dias', models.DecimalField(decimal_places=2, help_text='Días de vacaciones causados en el ciclo', max_digits=5, verbose_name='Días causados')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionContratos.t_contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Ciclo de vacaciones',
                'ordering': ['contrato', 'fecha_inicio'],
                'unique_together': {('contrato', 'fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
