# Generated by Django 6.0 on 2026-01-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ciclos_vacaciones',
            name='dias',
            field=models.IntegerField(help_text='Días de vacaciones causados en el ciclo', verbose_name='Días causados'),
        ),
    ]
