# Generated by Django 6.0 on 2026-01-27 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0021_t_contrato_sabado_habil'),
        ('gestionVacaciones', '0002_alter_t_ciclos_vacaciones_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_novedad_vac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'DISFRUTADAS'), ('C', 'COMPENSADAS')], max_length=1, verbose_name='Tipo de vacaciones')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('dias', models.IntegerField(help_text='Días tomados o compensados', verbose_name='Días')),
                ('dias_habiles', models.IntegerField(default=0, verbose_name='Días hábiles')),
                ('dias_no_habiles', models.IntegerField(default=0, verbose_name='Días no hábiles')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionVacaciones.t_ciclos_vacaciones', verbose_name='Ciclo de vacaciones')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionContratos.t_contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Novedad de vacaciones',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
