# Generated by Django 6.0 on 2026-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacaciones', '0003_t_novedad_vac'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_novedad_vac',
            name='fecha_fin_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin real'),
        ),
        migrations.AddField(
            model_name='t_novedad_vac',
            name='fecha_inicio_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio real'),
        ),
    ]
