# Generated by Django 6.0 on 2026-01-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacaciones', '0004_t_novedad_vac_fecha_fin_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_novedad_vac',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
