# Generated by Django 6.0 on 2026-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacaciones', '0005_t_novedad_vac_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_novedad_vac',
            name='base',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Base'),
        ),
    ]
