# Generated by Django 6.0 on 2026-01-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacaciones', '0006_t_novedad_vac_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_novedad_vac',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Base'),
        ),
    ]
