# Generated by Django 6.0 on 2025-12-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=6, verbose_name='Codigo cliente')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre cliente')),
                ('estado_cliente', models.BooleanField(default=True, verbose_name='Estado cliente')),
            ],
        ),
        migrations.CreateModel(
            name='t_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.CharField(max_length=6, verbose_name='Codigo empresa')),
                ('nit_empresa', models.CharField(max_length=20, verbose_name='Nit empresa')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razon social')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion empresa')),
                ('telefono', models.CharField(max_length=24, verbose_name='Telefono')),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='gestionClientes.t_cliente', verbose_name='Codigo clientes')),
            ],
        ),
    ]
