# Generated by Django 6.0 on 2026-01-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0002_usuarioempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_cliente',
            name='codigo_cliente',
        ),
    ]
