# Generated by Django 6.0 on 2026-01-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0003_remove_t_cliente_codigo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Celular'),
        ),
    ]
