# Generated by Django 6.0 on 2026-01-08 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0004_t_cliente_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_empresa',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Digito Verificacion'),
        ),
        migrations.AlterField(
            model_name='t_empresa',
            name='codigo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='gestionClientes.t_cliente', verbose_name='Cliente'),
        ),
    ]
