# Generated by Django 6.0 on 2025-12-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('ruta_jasper', models.CharField(help_text='Ruta interna al archivo .jasper', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('user_creator', models.CharField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('etiqueta', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(choices=[('str', 'Texto'), ('int', 'Entero'), ('date', 'Fecha'), ('bool', 'Booleano')], max_length=10)),
                ('requerido', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='gestionReportes.reporte')),
            ],
        ),
    ]
