from django.urls import path
from parametros.views import (tipos_contratosCreateView, tipo_contratosDeleteView, 
                              tipos_salariosCreateView, tipo_salariosDeleteView, 
                              tipos_cotizantesCreateView, tipo_cotizantesDeleteView,
                              subtipos_cotizantesCreateView, subtipo_cotizantesDeleteView,
                              bancosCreateView,bancosDeleteView,
                              entidadesssCreateView, entidadesssDeleteView,
                              t_conceptos_salarioCreateView,t_conceptos_salarioDeleteView,
                              tipo_nominaCreateView,tipo_nominaDeleteView,
                              parametro_generalCreateView, parametro_generalDeleteView,
                              parametro_DetalleCreateView,parametro_detalleDeleteView,
                              t_calendario_LaboralView, t_calendarioDeleteView)
urlpatterns = [
    path("tipos_contratos/", tipos_contratosCreateView.as_view(), name="tipos_contratos"),
    path("tipos_contratos_eliminar/<int:pk>/", tipo_contratosDeleteView.as_view(), name="tipos_contratos_eliminar"),
    path("tipos_salarios/", tipos_salariosCreateView.as_view(), name="tipos_salarios"),
    path("tipos_salarios_eliminar/<int:pk>/", tipo_salariosDeleteView.as_view(), name="tipos_salarios_eliminar"),
    path("tipos_cotizantes/", tipos_cotizantesCreateView.as_view(), name="tipos_cotizantes"),
    path("tipos_cotizantes_eliminar/<int:pk>/", tipo_cotizantesDeleteView.as_view(), name="tipos_cotizantes_eliminar"),
    path("subtipos_cotizantes/", subtipos_cotizantesCreateView.as_view(), name="subtipos_cotizantes"),
    path("subtipos_cotizantes_eliminar/<int:pk>/", subtipo_cotizantesDeleteView.as_view(), name="subtipos_cotizantes_eliminar"),
    path("bancos/", bancosCreateView.as_view(), name="bancos"),
    path("bancos_eliminar/<int:pk>/", bancosDeleteView.as_view(), name="bancos_eliminar"),
    path("entidades_ss/", entidadesssCreateView.as_view(), name="entidades_ss"),
    path("entidades_ss_eliminar/<int:pk>/", entidadesssDeleteView.as_view(), name="entidades_ss_eliminar"),
    path("conceptos_salario/", t_conceptos_salarioCreateView.as_view(), name="conceptos_salario"),
    path("conceptos_salario_eliminar/<int:pk>/", t_conceptos_salarioDeleteView.as_view(), name="conceptos_salario_eliminar"),
    path("tipo_nomina/", tipo_nominaCreateView.as_view(), name="tipo_nomina"),
    path("tipo_nomina/<int:pk>/", tipo_nominaDeleteView.as_view(), name="tipo_nomina_eliminar"),
    path("parametro_general/", parametro_generalCreateView.as_view(), name="parametro_general"),
    path("parametro_general/<int:pk>/", parametro_generalDeleteView.as_view(), name="parametro_general_eliminar"),
    path("parametro_general/<int:parametro_id>/parametro_detalle/", parametro_DetalleCreateView.as_view(), name="parametro_detalle"),
    path("parametro_general/<int:parametro_id>/parametro_detalle_eliminar/<int:pk>", parametro_detalleDeleteView.as_view(), name="parametro_detalle_eliminar"),
    path("calendario/", t_calendario_LaboralView.as_view(), name="calendario"),
    path("calendario/<int:pk>/", t_calendarioDeleteView.as_view(), name="calendario_eliminar"),


]