# Generated by Django 6.0 on 2026-01-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_conceptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_concepto', models.CharField(max_length=5, verbose_name='Codigo concepto')),
                ('desc_concepto', models.CharField(max_length=100, verbose_name='Descripcion concepto')),
                ('desc_concepto_eng', models.CharField(max_length=100, verbose_name='Descripcion en ingles')),
                ('tipo_concepto', models.CharField(choices=[('DEV', 'Devengo'), ('DED', 'Deduccion'), ('PRO', 'Porvision')], max_length=3, verbose_name='Tipo de concepto')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
