# Generated by Django 6.0 on 2026-01-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConceptos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_conceptos',
            name='cod_concepto',
            field=models.CharField(max_length=5, unique=True, verbose_name='Codigo concepto'),
        ),
    ]
