# Generated by Django 6.0 on 2026-01-06 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0002_usuarioempresa'),
        ('gestionConceptos', '0002_alter_t_conceptos_cod_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_concepto_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_concepto_emp', models.CharField(max_length=100, verbose_name='Descripcion concepto')),
                ('tipo_redondeo', models.CharField(choices=[('SR', 'Sin redondeo'), ('T', 'Truncar'), ('RA', 'Redondeo arriba'), ('RB', 'Redondeo abajo'), ('C', 'Centenar cercano')], max_length=2, verbose_name='Tipo de redondeo')),
                ('sin_valor', models.CharField(choices=[('0', 'Dejar linea en 0'), ('B', 'Borrar linea')], max_length=2, verbose_name='Sin valor')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('cod_concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConceptos.t_conceptos', verbose_name='Concepto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionClientes.t_empresa', verbose_name='Empresa')),
            ],
        ),
    ]
