# Generated by Django 6.0 on 2026-01-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0002_usuarioempresa'),
        ('gestionConceptos', '0003_t_concepto_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_concepto_empresa',
            options={'verbose_name': 'Concepto por empresa', 'verbose_name_plural': 'Conceptos por empresa'},
        ),
        migrations.AddConstraint(
            model_name='t_concepto_empresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'cod_concepto'), name='unique_concepto_por_empresa'),
        ),
    ]
