# Generated by Django 6.0 on 2026-01-09 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConceptos', '0004_alter_t_concepto_empresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_concepto_empresa',
            name='concepto_cliente',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Concepto cliente'),
        ),
        migrations.AddField(
            model_name='t_concepto_empresa',
            name='concepto_espejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepto_espejo', to='gestionConceptos.t_conceptos', verbose_name='Concepto espejo'),
        ),
    ]
