# Generated by Django 6.0 on 2026-01-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConceptos', '0005_t_concepto_empresa_concepto_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_conceptos',
            name='tipo_concepto',
            field=models.CharField(choices=[('DEV', 'DEVENGO'), ('DED', 'DEDUCCION'), ('PRO', 'PROVISION')], max_length=3, verbose_name='Tipo de concepto'),
        ),
    ]
