# Generated by Django 6.0 on 2026-01-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConceptos', '0006_alter_t_conceptos_tipo_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_grupo_concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_grupo_concepto_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConceptos.t_concepto_empresa', verbose_name='Concepto')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConceptos.t_grupo_concepto', verbose_name='Grupo')),
            ],
            options={
                'unique_together': {('grupo', 'concepto')},
            },
        ),
    ]
