# Generated by Django 6.0 on 2026-01-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConceptos', '0007_t_grupo_concepto_t_grupo_concepto_det'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grupo_concepto_det',
            name='operacion',
            field=models.CharField(choices=[('+', 'SUMAR'), ('-', 'RESTAR')], default='+', max_length=1, verbose_name='Operacion'),
            preserve_default=False,
        ),
    ]
