# Generated by Django 6.0 on 2026-01-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConceptos', '0008_t_grupo_concepto_det_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_concepto_empresa',
            name='sin_valor',
            field=models.CharField(choices=[('BO', 'BORRAR LINEA'), ('NB', 'NO BORRAR LINEA')], max_length=2, verbose_name='Sin valor'),
        ),
    ]
